-- Bloc 1 : Créer le moteur de calcul
CREATE WAREHOUSE IF NOT EXISTS HEALTH_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND   = 60
  AUTO_RESUME    = TRUE;

-- Bloc 2 : Créer la base de données
CREATE DATABASE IF NOT EXISTS HEALTH_DB;

-- Bloc 3 : Créer les 3 couches
CREATE SCHEMA IF NOT EXISTS HEALTH_DB.RAW;
CREATE SCHEMA IF NOT EXISTS HEALTH_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS HEALTH_DB.GOLD;

-- Bloc 4 : Vérifier
SHOW SCHEMAS IN DATABASE HEALTH_DB;