
-- KPI 1 : Répartition par statut et sexe
CREATE OR REPLACE TABLE HEALTH_DB.GOLD.KPI_STATUT_SEXE AS
SELECT
    SEXE,
    STATUT,
    COUNT(*)                            AS NB_PATIENTS,
    ROUND(AVG(AGE), 1)                  AS AGE_MOYEN,
    ROUND(AVG(CHOLESTEROL), 1)          AS CHOLESTEROL_MOYEN,
    ROUND(AVG(PRESSION_ARTERIELLE), 1)  AS PRESSION_MOYENNE,
    ROUND(AVG(FREQ_CARDIAQUE_MAX), 1)   AS FREQ_CARDIAQUE_MOYENNE
FROM HEALTH_DB.STAGING.PATIENTS_CLEAN
GROUP BY SEXE, STATUT
ORDER BY SEXE, STATUT;

-- KPI 2 : Taux de risque par tranche d'âge
CREATE OR REPLACE TABLE HEALTH_DB.GOLD.KPI_RISQUE_AGE AS
SELECT
    CASE
        WHEN AGE < 40 THEN '< 40 ans'
        WHEN AGE < 55 THEN '40-54 ans'
        WHEN AGE < 65 THEN '55-64 ans'
        ELSE '65 ans et +'
    END                                         AS TRANCHE_AGE,
    COUNT(*)                                    AS NB_PATIENTS,
    SUM(CASE WHEN STATUT = 'Malade' THEN 1 ELSE 0 END) AS NB_MALADES,
    SUM(CASE WHEN STATUT = 'Sain' THEN 1 ELSE 0 END)   AS NB_SAINS,
    ROUND(
        SUM(CASE WHEN STATUT = 'Malade' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 1
    )                                           AS TAUX_RISQUE_PCT
FROM HEALTH_DB.STAGING.PATIENTS_CLEAN
GROUP BY TRANCHE_AGE
ORDER BY TAUX_RISQUE_PCT DESC;

-- KPI 3 : Impact du cholestérol sur le statut
CREATE OR REPLACE TABLE HEALTH_DB.GOLD.KPI_CHOLESTEROL AS
SELECT
    CASE
        WHEN CHOLESTEROL < 200 THEN 'Normal (< 200)'
        WHEN CHOLESTEROL < 240 THEN 'Limite (200-239)'
        ELSE 'Élevé (240+)'
    END                                         AS NIVEAU_CHOLESTEROL,
    STATUT,
    COUNT(*)                                    AS NB_PATIENTS,
    ROUND(AVG(AGE), 1)                          AS AGE_MOYEN
FROM HEALTH_DB.STAGING.PATIENTS_CLEAN
GROUP BY NIVEAU_CHOLESTEROL, STATUT
ORDER BY NIVEAU_CHOLESTEROL, STATUT;

-- KPI 4 : Profil détaillé par type de douleur thoracique
CREATE OR REPLACE TABLE HEALTH_DB.GOLD.KPI_DOULEUR AS
SELECT
    TYPE_DOULEUR,
    STATUT,
    COUNT(*)                                AS NB_PATIENTS,
    ROUND(AVG(AGE), 1)                      AS AGE_MOYEN,
    ROUND(AVG(FREQ_CARDIAQUE_MAX), 1)       AS FREQ_CARDIAQUE_MOYENNE,
    ROUND(AVG(DEPRESSION_ST), 2)            AS DEPRESSION_ST_MOYENNE,
    ROUND(
        SUM(CASE WHEN STATUT = 'Malade' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 1
    )                                       AS TAUX_RISQUE_PCT
FROM HEALTH_DB.STAGING.PATIENTS_CLEAN
GROUP BY TYPE_DOULEUR, STATUT
ORDER BY TAUX_RISQUE_PCT DESC;

-- KPI 5 : Corrélation fréquence cardiaque et risque
CREATE OR REPLACE TABLE HEALTH_DB.GOLD.KPI_FREQ_CARDIAQUE AS
SELECT
    CASE
        WHEN FREQ_CARDIAQUE_MAX < 120 THEN '< 120 bpm'
        WHEN FREQ_CARDIAQUE_MAX < 150 THEN '120-149 bpm'
        WHEN FREQ_CARDIAQUE_MAX < 170 THEN '150-169 bpm'
        ELSE '170+ bpm'
    END                                     AS TRANCHE_FREQ,
    STATUT,
    COUNT(*)                                AS NB_PATIENTS,
    ROUND(AVG(AGE), 1)                      AS AGE_MOYEN,
    ROUND(
        SUM(CASE WHEN STATUT = 'Malade' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 1
    )                                       AS TAUX_RISQUE_PCT
FROM HEALTH_DB.STAGING.PATIENTS_CLEAN
GROUP BY TRANCHE_FREQ, STATUT
ORDER BY TRANCHE_FREQ;

-- KPI 6 : Score de risque global par patient
CREATE OR REPLACE TABLE HEALTH_DB.GOLD.KPI_SCORE_RISQUE AS
SELECT
    PATIENT_ID,
    AGE,
    SEXE,
    STATUT,
    CHOLESTEROL,
    PRESSION_ARTERIELLE,
    FREQ_CARDIAQUE_MAX,
    DEPRESSION_ST,
    TYPE_DOULEUR,
    -- Score de risque calculé
    ROUND(
        (CASE WHEN STATUT = 'Malade' THEN 30 ELSE 0 END) +
        (CASE WHEN AGE > 55 THEN 20 ELSE 10 END) +
        (CASE WHEN CHOLESTEROL > 240 THEN 20 ELSE 5 END) +
        (CASE WHEN PRESSION_ARTERIELLE > 140 THEN 15 ELSE 5 END) +
        (CASE WHEN FREQ_CARDIAQUE_MAX < 130 THEN 15 ELSE 5 END)
    , 0)                                    AS SCORE_RISQUE
FROM HEALTH_DB.STAGING.PATIENTS_CLEAN;



-- Vérification
SELECT * FROM HEALTH_DB.GOLD.KPI_RISQUE_AGE;
SELECT * FROM HEALTH_DB.GOLD.KPI_STATUT_SEXE;
SELECT * FROM HEALTH_DB.GOLD.KPI_CHOLESTEROL;
SELECT * FROM HEALTH_DB.GOLD.KPI_DOULEUR;
SELECT * FROM HEALTH_DB.GOLD.KPI_FREQ_CARDIAQUE;
SELECT * FROM HEALTH_DB.GOLD.KPI_SCORE_RISQUE;